apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: answer-ai
  name: answer-ai-pvc
  namespace: answer-ai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi