apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: answerai
  name: answerai-pvc
  namespace: answerai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi