apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: answerai-ingress
  namespace: answerai
  #annotations:
    # Use appropriate annotations for your Ingress controller, e.g., for NGINX:
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: answerai.minikube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: answerai-service
            port:
              number: 8080
